# Generated by Django 3.1.7 on 2021-03-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course_teach',
        ),
        migrations.AddField(
            model_name='staff',
            name='course_teach',
            field=models.ManyToManyField(blank=True, null=True, to='sms_app.Course'),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subject_teach',
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_teach',
            field=models.ManyToManyField(blank=True, null=True, to='sms_app.Subject'),
        ),
    ]
