# Generated by Django 3.1.7 on 2021-04-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_auto_20210402_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sms_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sms_app.sessionyear'),
        ),
    ]
