# Generated by Django 3.1.7 on 2021-05-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20210511_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='attendence_type',
            new_name='attendance_type',
        ),
    ]
