# Generated by Django 3.1.7 on 2021-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_auto_20210517_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_demo.png', null=True, upload_to=''),
        ),
    ]
