# Generated by Django 3.1.7 on 2021-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_auto_20210523_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar-8.jpg', null=True, upload_to=''),
        ),
    ]
